[package]
name = "peach_profiler"
edition = "2024"
version = "0.1.3"
authors.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
peach_metrics = { version = "0.1.2", path = "../peach_metrics" }
peach_pit = { version = "0.1.3", path = "../peach_pit" }


### FEATURES #################################################################

[features]
# Enables the profiler. Running a program without the profile feature disables 
# the profiler and will not affect the program's execution.
profile = ["peach_pit/profile"]
