[package]
name = "peach_profiler"
edition = "2024"
version = "0.1.7"
authors.workspace = true
description.workspace = true
license.workspace = true
readme = "../crates-io.md"
repository = "https://github.com/Austionian/peach_profiler"

[dependencies]
peach_metrics = { version = "0.1.3", path = "../peach_metrics" }
peach_pit = { version = "0.1.4", path = "../peach_pit" }


### FEATURES #################################################################

[features]
default = []

# Enables the profiler. Running a program without the profile feature disables 
# the profiler and will not affect the program's execution.
profile = ["peach_pit/profile"]

# Make sure to create the documentation with the profiler enabled.
[package.metadata.docs.rs]
rustc-args = ["--features", "profile"]
