[workspace]
resolver = "3"
members = ["peach_pit", "peach_profiler", "platform_metrics"]

[workspace.package]
version = "0.1.0"
authors = ["Austin Rooks"]
description = "A performant, low-overhead profiler. Just peachy."
