[workspace]
resolver = "3"
members = ["peach_pit", "peach_profiler", "peach_metrics"]

[workspace.package]
authors = ["Austin Rooks"]
description = "A performant, low-overhead profiler. Just peachy."
license = "MIT OR Apache-2.0"

[workspace.lints.clippy]
pedantic = { level = "warn" }
