[package]
name = "peach_metrics"
edition = "2024"
version = "0.1.3"
authors.workspace = true
description.workspace = true
license.workspace = true
repository = "https://github.com/Austionian/peach_profiler"

[dependencies]
libc = "0.2"
windows-sys = "0.61.0"
